[technote]
id = "SITCOMTN-155"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-155.lsst.io"
github_url = "https://github.com/lsst-sitcom/sitcomtn-155"
github_default_branch = "main"
date_created = 2025-02-10T14:47:43Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Manuel"
name.family = "Gomez Jimenez"
internal_id = "gomezm"

[[technote.authors.affiliations]]
name = ""
internal_id = ""
address = ""
